language:
    - julia
os:
  - linux
  - osx
julia:
  - nightly
  - 1.0
matrix:
    allow_failures:
        - julia: nightly
notifications:
  email: false
before_script:
    - cp test/Manifest.toml .
after_success:
  - julia --project=coverage/ -e 'using Pkg; Pkg.instantiate()'
  - julia --project=coverage/ coverage/coverage.jl
